const voters = {
    //7A-1
    "tes": "1a2b3c",
    "Abimanyoe Aryo Halim": "xP7aB4qJ",
    "Affan Jailani Haehap": "mQ9rT3vL",
    "Afiqah Ayudia Nimeesya Nasution": "gK8wY6zC",
    "Alfian Rizkie Lubis": "hF4jP7kX",
    "Alvaro Zhaliandy": "zN2mQ9sD",
    "Aviqah zahran Ghaisani": "pW3xT6vB",
    "Dhaffin Azka Putra Darmawan": "rM8kG5yZ",
    "Fayra Azwa Maraksa": "tJ9nF4pH",
    "Gibran Ramadhan Wijaya Hasrimi": "qL7bD8xC",
    "Hafiz Al Rasyid": "vN3yP6kQ",
    "Hisyam Dzaky Islamy Lubis": "kH9jL4wT",
    "Ilham Raihan Sukamoto": "mC7gZ5qV",
    "Latisha Adzra Handoko": "yP8nJ3xR",
    "M Azka Fanani Daulay": "wT6vK9pB",
    "MIchelle Jentra Tarigan": "gF4kN7sM",
    "Muhammad Rafi": "aJ5yH8qX",
    "Oktha Pratama Kaban": "zQ9wP6mC",
    "Qinala Windriadi": "rL8tK4jG",
    "Rafif Akhdan Faika": "xH3pN7qT",
    "Rieca Fajrina Hafizah Lubis": "mD6gW9yV",
    "Rifan Arezqi": "kN4jL8pB",
    "Sabina Hafidzah Abira Lubis": "pC7xM3wT",
    "Shazia Asha Aufi": "tF9vG6yH",
    "Siti Haliza Munirah": "yJ8kP5qX",
    "Syahira Ulfa": "rT3gN9pL",
    "Syaira Aqifa Naila": "mH6wF8kC",
    "Syifa Azhara Winata": "aL7yK4qV",
    "Zaskia Amira": "zP9tM3xG",
    "Zhafif Amadeo Syahputra": "kJ8nH6wB",

    //7B-1
    "Abizard Oezil Anindra": "vT3yK9pL",
    "Agha Ihsan Yustana": "mH6gW8kX",
    "Aliya Nadira Hasibuan": "aF7nJ4qC",
    "Alvaro Virendra Tarigan": "zP9tM6xV",
    "Anindya Gothra Athidira ": "kL8jH5wB",
    "Dzaka Hanan Lathif": "rT4gN9pQ",
    "Faidh Arkan Mauranda Hsb": "mJ6wF8kC",
    "Hadif Rizki Ramadhan": "yL7yK4qV",
    "Hafidz Rafiandra Nasution": "pT9tM3xG",
    "Jihan Talita Ulfa": "kJ8nH6wB",
    "Khaira Syarafana Ramadhani": "xT3yK9pL",
    "Melody Nasyitha Salsabila Siagian": "mH6gW8kX",
    "Mhd Rafa Nurwan": "aF7nJ4qC",
    "Muhammad Alfaiz Mahadika": "zP9tM6xV",
    "Muhammad Anggi Nafil Siregar": "kL8jH5wB",
    "Muhammad Fikri Pratama": "rT4gN9pQ",
    "Naira Salsabila": "mJ6wF8kC",
    "Natasya Hummaira Ilham": "yL7yK4qV",
    "Putri Bintang Rania": "pT9tM3xG",
    "Rasya Alfaruq Haristian": "kJ8nH6wB",
    "Razwa Azzahra Ginting": "xT3yK9pL",
    "Rizky Aditya Artami": "mH6gW8kX",
    "Sofhia Nakita Ufairah": "aF7nJ4qC",
    "Sutan Kemal Artanugroho": "zP9tM6xV",
    "T Diaz Syahputra": "kL8jH5wB",
    "Tengku Farradiba Queen Nurin Fausyah Noor": "rT4gN9pQ",
    "Tiara Hana Simargolang": "mJ6wF8kC",
    "Xaquille Aazraqi Al Asag": "yL7yK4qV",
    "Zareena Zahra Hanania": "pT9tM3xG",
    "Zivanna Arizta Putri": "kJ8nH6wB",

    //7C-1
    "Al- Aqsha Dayyan Fathani Setyawan": "gK9nJ7pX",
    "Alby Husain Hasibuan": "wT4xL8qM",
    "Allora Chantiqa Hanan": "mF6yK3vC",
    "Annisa Maharany Tarigan": "rJ9gH5kQ",
    "Azka Hidayat Bahri Nasution": "xL7nP8qV",
    "Chairul Ramadhan Siregar": "zH4wF9tB",
    "Danesh Xavier Sibagariang": "kP8jG6mT",
    "Fairuz Barkah Hudaibi Panggabean": "aM3nJ7vL",
    "Fondstella Sulaiman": "tD6yK9pQ",
    "Hafizh Agna Zulfahmi": "yL8kF4wX",
    "Hanifa Dzakiyah": "mG7nP5qC",
    "Kamilah Adlillah Tahel": "rJ9gT3vH",
    "Kechia Nikita Shaqi": "xL6nK8pV",
    "Khaniya Shalu Ahmad": "zH4wF9tB",
    "Makhzuhra Zihni Tanjung": "kP8jG6mT",
    "Muhammad Arzaq Zhafran Sitorus": "aM3nJ7vL",
    "Muhammad Dzaky Kamil": "tD6yK9pQ",
    "Muhammad Ibrahim": "yL8kF4wX",
    "Muhammad Rizky Husaini": "mG7nP5qC",
    "Nafisah Zafirah Roseno": "rJ9gT3vH",
    "Naurah Hayyu": "xL6nK8pV",
    "Noval Prayoga": "zH4wF9tB",
    "Prince Hessel Akbar Sirait": "kP8jG6mT",
    "Raina Ghasani Mahbub": "aM3nJ7vL",
    "Rezki Wira Pratama": "tD6yK9pQ",
    "Sultan Ahmad El Fath Nasution": "yL8kF4wX",
    "Syakhira Nadine Tampubolon": "mG7nP5qC",
    "Syifa Syaqila": "rJ9gT3vH",
    "Yuriashila Sastra Maheswari": "xL6nK8pV",
    "Zibran Garin Nurseha": "zH4wF9tB",

    //7D-1
    "Airlangga Yudha Zandra": "hG9nJ7pX",
    "Aisyah Kasyifa": "vT4xL8qM",
    "Alun Naditya": "nF6yK3vC",
    "Awfar Achsan Sibuea": "qJ9gH5kQ",
    "Ayira Kamila": "xL7nP8qV",
    "Defa Aqeel Pranaja": "zH4wF9tB",
    "Dyaz Saamiy Muhammad": "kP8jG6mT",
    "Dzikri Aqilah Fildzah Papilaya Pasaribu": "aM3nJ7vL",
    "Gybran Jogi": "tD6yK9pQ",
    "Haikal Irawan Damanik": "yL8kF4wX",
    "Kayyisa Elma Mazea": "mG7nP5qC",
    "Khaira Zuhra Alwi": "rJ9gT3vH",
    "Khansa Alesha Farzana": "xL6nK8pV",
    "Miqeyza Safeeka": "zH4wF9tB",
    "Mona Syakira Ritonga": "kP8jG6mT",
    "Muhammad Azzam Faisal Lubis": "aM3nJ7vL",
    "Muhammad Ibrahim Kelana": "tD6yK9pQ",
    "Muhammad Reza Al Fatih Daulay": "yL8kF4wX",
    "Nadira Shahana": "mG7nP5qC",
    "Najwan Azhim Tiofani": "rJ9gT3vH",
    "Ovick Syathir Hajid": "xL6nK8pV",
    "Putri Sakinah Siregar": "zH4wF9tB",
    "Rachel Rizkia Putri": "kP8jG6mT",
    "Rafaat Akbar Ar Rafie Simbolon": "aM3nJ7vL",
    "Rifqie Khairy Rachman": "tD6yK9pQ",
    "Shabara Zhafiray Syafhas": "yL8kF4wX",
    "Sutan Arfa Harahap": "mG7nP5qC",
    "T Zalikha Rizqy Tafly": "rJ9gT3vH",
    "Yuriqani Berlian Sayuti": "xL6nK8pV",
    "Zia Falisha Arthajaya": "zH4wF9tB",

    //8E-1
    "Al Fath Aqil Khaleev": "dK7pL9mX",
    "Alifsyah Alaric Pasaribu": "mT3yG6qV",
    "Alisha Azizi Purboyo": "hN4jW8kC",
    "Alya Dayana Putri Wilhan": "pL9xH5wB",
    "Amiira Dafina Ulya": "zT6kM8qC",
    "Asya Dzahin Pulungan": "gF3jL7pX",
    "Azura Khansa Shafia": "kN9mH4wV",
    "Bagas Fathan Atthoriq": "rP6tK8qG",
    "Balqisya Nailah Frinando": "xJ4wF9tM",
    "Ben Aiy Muhammad": "vT3kG7pL",
    "Danish Abrisham Harahap": "mH9nL6wB",
    "Danish Faeyza Ahmad": "aF4pK8qV",
    "Danish Riffat Fathullah": "zT7xM3wC",
    "Dzaki Azkatyaga Tarigan": "kJ6gH9pX",
    "Dzargi Aufa Darshah": "pN8mL5qG",
    "Fariz Abrar Alghaisan Daulay": "xT3kF7wB",
    "Hafidh Arya Ananda": "mJ9nH6pL",
    "Karina Nur Shidqia Siregar": "rF4tK8qV",
    "Kaysha Almahira Nasution": "zT7xM3wC",
    "Khalyla Swietenia Ivana Noor": "kJ6gH9pX",
    "M Azzan Islami": "pN8mL5qG",
    "Mahirah Shabir": "xT3kF7wB",
    "Malik Ahmad Bairawi": "mJ9nH6pL",
    "Muhammad Albany Athayaa Adnani": "rF4tK8qV",
    "Muhammad Azzam Mubarak": "zT7xM3wC",
    "Qalila Faci Nasution": "kJ6gH9pX",
    "Raditya Wijaya Simatupang": "pN8mL5qG",
    "Raffi Caesar Barus": "xT3kF7wB",
    "Salsabila Az-Zahra Batubara": "mJ9nH6pL",
    "Shibaa Rumaisha Nur": "rF4tK8qV",
    "Sultan Akhtar Syarif": "zT7xM3wC",
    "Yaffa Azita Hutabarat": "kJ6gH9pX",

    // 8A-1
    "Ahmad Fahri Alkhalifi": "x2f7a9pQ",
    "Akmal Ikhsan Winandar": "L9k1m3tZ",
    "Amira Tsary Putri Hermawan": "c8V4w2rT",
    "Arkandhana Azka Fahmi": "p6J9h0eB",
    "Audrey Keysha Az Zahra": "q1M7x8nL",
    "Bazliah Salma": "f5H2j9sD",
    "Danish Azka Arraziq": "z4R8p6cQ",
    "Diva Aish Syakira": "n3T7b1mV",
    "Diza Khansa Mazaya": "u9K2v5gH",
    "Dyandra Audrey Feiza": "r6L3d7pJ",
    "Faiz Rizqullah Pratama Zulad": "b8F5h4zK",
    "Ibrah Rustina Utani Lubis": "x3J7k9qM",
    "M Marsa Amza Shauqi": "t5P1z8nG",
    "M Rafli Faiz": "k9H3m4rL",
    "M Dzakwan Athalah Fidoli Siregar": "s4V6b2qN",
    "Malikha Queen Azmi": "e7D9p0hB",
    "Malikha Zavania Arasya": "y2N4w8fK",
    "Mangarap Batang Taris Hasibuan": "v6G5r3zQ",
    "Muhammad Ar Rasyid Hutasuhut": "m1H8k9xR",
    "Muhammad Raka Alfarsi Damanik": "o7J4p2tS",
    "Muhammad Pekokyah Taringan": "i9Q6z3gL",
    "Muhammad Zafran Ghaffar": "a3R7x8nK",
    "Nabila Yasmin Hashifah": "d5W1b9hQ",
    "Nayra Octiva Renadha": "g8F2k4rJ",
    "Radithya Arkaan Siregar": "w3E7p5mT",
    "Shira Apriliana": "u9M4k6dB",
    "Sis Suatmaja": "z2H8t3nL",
    "Sofia Kamila Harahap": "q5K1p9cJ",
    "Syafira Karunia Siregar": "f7V4r6mQ",
    "Syarifah Alya Azmi Pulungan": "l3N9x2dH",
    "T Hassan Quinn": "b6P7j8gT",
    "Zahirah Nurul Adha": "o1K5m4vR",

    // 8B-1
    "Adelia Faranisa Zava": "a8f7c2e9",
    "Ahmad Fadhil Arafat Addari Nasution": "b9d3k4h1",
    "Alvino Ghaisan Aprilio Wiryadi": "c4e6j8m2",
    "Athaa Atsiliah Infanto": "d1f9p7r3",
    "Azka Igri Raihanah": "e5g3k2n8",
    "Bella Azzalea": "f2h6m4q1",
    "Cheszka Najla Nathifa": "g7j9p8s5",
    "Daafa Alfari Pohan": "h3k2l8n7",
    "Dipta Mahija Valiant": "i6m4n2r5",
    "Eza Ahmadi Neazad": "j8n3p7q4",
    "Farhan Abrar Natawo": "k1p6r5s8",
    "Felisha Azzahra Rizal": "l9q4s8t2",
    "Irfan Yusran Berutu": "m2r8t6u5",
    "Khairuna Rizka Manik": "n5s3u7v1",
    "M Raka Putra Balka": "o8t4v2w6",
    "Muhammad Al Ghifari Rozi Hasibuan": "p1u9w3x7",
    "Muhammad Daanish Gading Al-Hafiz": "q3v5x4y2",
    "Muhammad Ghafiral Khatna": "r7w2y6z8",
    "Muhammad Luthfi Hasibuan": "s4x8z3a1",
    "Nafekha Janetta Khairum": "t6y5a2b7",
    "Naura Nurfahani Detra": "u2z3b4c8",
    "Novan Al Habsy": "v8a7c6d3",
    "Raiz Putra Akbar Ginting": "w1b9d5e4",
    "Rakan Khadafi Pohan": "x3c4e7f9",
    "Rizky Alifia Harista": "y5d6f2g8",
    "Rr Byanca Atthahirah Avgie": "z7e3g1h5",
    "Shafina Natasha Rudi": "a4f5h8i2",
    "T Dilfa Maulana": "b6g7i3j9",
    "Tengku Said Achmad Raffli": "c8h2j4k6",
    "Yafe Syauqie Bariqa": "d1i9k5l8",
    "Zeeshan Arkaan": "e3j6l2m7",

    // 8C-1
    "Aldrich Azka": "f4k7m3n9",
    "Alisya Dia Zahira": "g6l8n4o1",
    "Audy Ashalina": "h9m2o5p6",
    "Azman Rizvan": "i3n7p8q2",
    "Baim Putra Gunawan": "j5o9q6r3",
    "Bintang Luthfi Ardana": "k8p1r7s4",
    "Carissa Putri Suhana": "l2q4s8t9",
    "Dastan Noushzad Anindra": "m6r3t2u5",
    "Fadhil Muhammad Althaf": "n9s5u4v7",
    "Fitiya Rupani Purba": "o1t7v3w8",
    "Ghania Nahiza Faira Pane": "p4u6w9x1",
    "Hana Ilmi Zahra": "q7v8x2y3",
    "Khanaya Adilla Siregar": "r2w3y5z9",
    "M Habib Haikal": "s6x7z1a4",
    "Maulana Irham Nasution": "t8y9a2b5",
    "Muhamad Alkahfi Akbar Triasa": "u3z4b6c7",
    "Muhammad Zaki Fadhillah": "v5a7c9d2",
    "Nabihan Azima Khaira": "w8b9d3e6",
    "Nadhira Feliza": "x2c4e5f7",
    "Naufal Hilmi Maika": "y7d8f6g1",
    "Nikesha Khalish Fawnia": "z9e3g7h8",
    "Qafka Deka": "a3f5h2i9",
    "Qalisya Daniya Rahman": "b4g6i8j2",
    "Raisa Rafania Siddik Lubis": "c7h9j3k5",
    "Raya Bening Batubara": "d1i2k4l8",
    "Razil Uwais Nuzula Pulungan": "e6j8l9m3",
    "Rifath Gizlan Arafah": "f9k1m5n7",
    "Rizqa Muyassarrah Puan Handoyo": "g2l3n8o4",
    "Sabqi Wistara Syarief Siregar": "h5m6o9p2",
    "Siti Aisyah Ramadhani Simanjorang": "i8n7p3q6",
    "Syahira Inayah Rizqi": "j3o4q5r8",

    // 8D-1
    "Alghifari Anindra Taufik": "k1r5t8u3",
    "Alisha Azzahra Nasution": "l4s6u9v7",
    "Argie Anargia Al Fath": "m7t8v2w4",
    "Arsyaqila Mianda Mahdi": "n2u3w5x6",
    "Arya Abisenna Nugroho": "o5v6x8y2",
    "Atha Pagoh Logani Ginting": "p8w9y1z4",
    "Balqis Adzra": "q1x2z3a7",
    "Devanta Arfa Aydin": "r3y4a5b8",
    "Encik Zhafira Deliza Fitri": "s6z7b9c1",
    "Eshal Akifa Naila": "t9a1c2d3",
    "Ilfana Amelia Audry": "u2b3d4e9",
    "Keanu Athallah Akbar Pohan": "v5c6e7f2",
    "Michi Soesanto Putri": "w8d9f1g3",
    "Muhammad Faizi Santoso": "x1e2g3h4",
    "Muhammad Nabil Hibatullah": "y3f4h5i7",
    "Muhammad Rafki Abgory Ginting": "z6g7i8j1",
    "Muhammad Umar Khalid": "a9h1j2k4",
    "Najwa Khalilah Putri Riawan": "b2i3k5l6",
    "Omar Fattahul Muhammad Hasibuan": "c4j5l7m8",
    "Rafa Atharizz Ryandra": "d7k8m9n2",
    "Raisya Salsabila Hsb": "e1l2n3o4",
    "Raziq Naufal Ritonga": "f3m4o5p9",
    "Sarah Afifah Syahrun": "g5n6p7q1",
    "Senandung Zuhrah Fadhilah Hafel": "h7o8q9r2",
    "Shanaz Azura": "i9p1r2s3",
    "Shofi Aisyah Aqila Panjaitan": "j2q3s4t5",
    "Syahirah Az-Zahra Batubara": "k4r5t6u7",
    "Sylvana Nursakinah Hafid Raditya": "l6s7u8v9",
    "Tengku Anaqie Anhar Sinar": "m8t9v1w2",
    "Thabrani Manurung": "n1u2w3x4",
    "Zhya Ziandra Kurniawan": "o3v4x5y6",
    "Zidan Ali Haziq": "p5w6y7z8",

    // 8E-1
    "Adinda Aisyah Raisya Fairuziah": "aX3pWq7L",
    "Alexa Angelica": "kM8rJs2N",
    "Anayya Shafa Nur Khalila": "zR5gVh9Q",
    "Angga Pranata Tarigan": "uT7dXc4P",
    "Assyifa Aurelia Putri": "oL9kQm3S",
    "Ayesha Ghina Khairaf": "bH6rTp8Z",
    "Bayu Langit Samudera": "dJ4yFs6X",
    "Faeyza Dira Utama Lubis": "mC8nVr5H",
    "Fajri Iksan Tumangger": "wP3kZs7B",
    "Fathan Raziqy Adwin": "hS6qMp4V",
    "Fayaadh Al Asag": "jL2vGh9D",
    "Firza Adelia Br Sembiring": "gN7xKp1Q",
    "Kayla Qonita": "tD5yWm8L",
    "Keano Nayaka Rauf Ginting": "rF4kXp3C",
    "Khalisa Aruna Arsanggayu": "nG6dVq7T",
    "M Rasya Athaya ": "xQ8mJh2Z",
    "Muhammad Audri Khaliq": "lH9sWp4B",
    "Muhammad Fachrul Rozi": "cJ3gKr7M",
    "Muhammad Gilang Faliandra": "vN5tHp8L",
    "Muhammad Ilham Arifin": "fS7xWq2G",
    "Muhammad Reyhan Akbar": "yP4mVh9D",
    "Mutia Ghassania": "kR6dXp5J",
    "Nabillah Marsha Fahira Rehulina Sen": "qT8sGh3L",
    "Radanica Latifah Br Tarigan": "pC5kVm7H",
    "Raffa Ansori Hutasuhut": "eL9tQp4X",
    "Rasikha Khairiyah Nasution": "zN2vGh8K",
    "Risa Ramadhani": "oJ6mWp3T",
    "Shadrina Zaahira Lubis": "gF4dXs9B",
    "Shazfa Khayyiirah A Fazri": "uH7kQm2P",
    "Shiffa Aura Syafira": "aT3yVp6L",
    "Siti Raisya Syabilah": "wC9rGm5X",
    "Zhahran Prayata Nugroho": "hP2kJs8D",
    "Zianka Ameera Zibacher": "mL5vXp4Q",
    
    // 9A-1
    "Alexandria Aulia Putri Sitorus": "Vw6b9pXc",
    "Alfathir Radeno Hendrik": "fH3kL1sZ",
    "Alya Alviona Sinaga": "mX7aK9qB",
    "Arif Satria Dirga": "Qz2hT8rD",
    "Arsyla Ghafar Pasaribu": "nJ5vG4pM",
    "Athira Shofia Putri Syahdina": "bR9xL7fC",
    "Carissa Ifra Naznin": "kW4qH2mS",
    "Carrisa Putri Ramadhani Azhar": "zF8pN3kV",
    "Daanish Sheraz Gusnanda": "yM1hT9rQ",
    "Duta Mulya Ramadhan": "tP6cV5zN",
    "Fabian Ramadhan Sitohang": "eK3xL8wG",
    "Fitra Hadisyah Pohan": "jQ7nR2hM",
    "Ghozy Aushaf Hibrizi": "uV4bT1kD",
    "Jayidan Akhtar": "oS5gM8zQ",
    "Kanaya Tabitha Lase": "cX9kL6fP",
    "Khalid Furqanul Muhammad Hsb": "dH2wG3nT",
    "M Arka Islami": "sF8vN1kJ",
    "Mahnasya Athira Zaira": "qW7pR9xL",
    "Muhammad Ariq Ar Rafi": "vK4nM2hP",
    "Muhammad Haisan Afsar": "gT9cJ7wS",
    "Muhammad Raka Khadafi": "aP3kL8zF",
    "Nauval Hazel Azzaki": "mH6vG2rJ",
    "Nazilla Azzahra Lubis": "xW1qN9tC",
    "Rafie Naufal P Siregar": "zL5pH3vG",
    "T Rafar Rizky": "jT8kM2rQ",
    "Ullaya Tsabitah Masyurah S": "kN9cL7hP",
    "Vidic Wira Ihsani": "bF3wG6pS",
    "Zivana Puti Anggraini": "uR4nM8vJ",

    // 9B-1
    "Afifah Talita Sakhi": "tY3mL7pH",
    "Alfio Raffasya Keiza": "gR9nK4zD",
    "Alifa Tsabitha": "pX8qL2fW",
    "Alvero Ghani": "vT6hJ9mS",
    "Alvino Alifiandra Adjie": "nF2cG8kL",
    "Annisa Rayani": "dM7pQ3rH",
    "Assyifa Adzra Syuhada": "sK9nV4tG",
    "Aufa Nathan Purnomo": "aL3kM6wP",
    "Bil Bram Argantara Adetya": "yT8hR2jC",
    "Daffa Khairan Lathif": "wF5cL9vN",
    "Dinda Almira Lavenia": "kH2nM8pS",
    "Falih Sulaiman Prasetyo": "qP4xT7rJ",
    "Fitri Mutiara Ambri": "zL1hG3kM",
    "Ghazi Fisyabi Al-Fatih": "uR9nJ6vP",
    "Hana Mardiah": "oS3pK7fG",
    "Keisya Putry Anandita": "mF8cN2wT",
    "Khairun Nizam Husein": "dX4hL6pQ",
    "M Dannesh Syahdian Hamonangan Siregar": "pK9mJ3rH",
    "M Fitra Hidawi": "fT1cV7nW",
    "Mhd Alfathir Rizqullah": "gH6xL8pD",
    "Mikail Al Khalifi Nugroho": "aN3tJ9kM",
    "Muhammad Arkan Khedira Asrul": "sV5hM2rQ",
    "Muhammad Azzam Akram": "zF8kN1wP",
    "Muhammad Habib Aldafi Sulistyo": "nT7mG4pS",
    "Muhammad Naufal": "kR2xL9hC",
    "Naila Syafia": "dP6vJ3rT",
    "Nayla Asylla Putri": "bX1hM8kW",
    "Nazrah Muliana Siregar": "uH4pG9nD",
    "Queen Uno Carrisa Siregar": "qK7mL2tS",
    "Rasya Putra Adinata": "jF5nN6rP",
    "Syafa Az-Zahra": "oM8kT1wH",

    // 9C-1
    "Ahmad Asyam Nas Hasibuan": "hL3nM8pT",
    "Aila Azra Anindita": "zK6cJ9rH",
    "Arbaa Erlangga": "gF4vL2tM",
    "Arkand Harith Jauhari": "pR1hN7kS",
    "Asyfa Rahma Alya Muzakir": "vX8mT3wP",
    "Dewandy Ahsan": "mK5nG9pC",
    "Fadhilah Aqila Pardosi": "sH2cL8rJ",
    "Faiq Danial": "dN7kM3tW",
    "Fathan Akram Natawo": "oP4hJ9mG",
    "Fayyadh Afandi Pasaribu": "aL6vG2pH",
    "Hasby Putra Arlinsyah": "fT8nK1rQ",
    "Jerico Mas'ud Sambahar Matondang": "kM9pL3tS",
    "Jivy Oktavianti": "qR2cN7wH",
    "Marsha Ramadani Kelana": "zH5hG4pD",
    "Muhamad Adikara Aqil Miftah": "nX3kL8tM",
    "Muhammad Adzka Danendra Zein": "uF7mJ9rS",
    "Muhammad Argadika Rubiliano": "dT1nM6wP",
    "Muhammad Fariz Bramantya": "gK8hG2pH",
    "Muhammad Naufal Alfarisy": "aR4cJ3kD",
    "Muhammad Rafan": "sM9pL7vW",
    "Naura Zhafira Ahmad": "pX2tN8rH",
    "Naya Desyifa": "jL5kG3pT",
    "Omar Ghazi Hawali": "oF7nH4wM",
    "Raziq Athaillah Mauranda Hasibuan": "fT8mK2pD",
    "Sabita Amanda Br Ginting": "qH1vJ9rG",
    "Tengku Samara Lady Fausyah Noor": "kM6nG3tP",
    "Ubaid Alif": "zR4hL8wH",
    "Zalfa Athifah": "uP9kN2mS",

    // 9D-1
    "Adisty Fahira Harahap": "hF7nL3pG",
    "Anugrah Pratama Shaka": "vT2cJ8rH",
    "Arka Wardana": "gM5kN1wP",
    "Azmih Rahman Lubis": "oK9mG4tS",
    "Azrina Khalila Iqtidar": "aR3nL7pH",
    "Chiara Shakayla Azalea Papilaya Pasaribu": "jH6cM2rG",
    "Cut Aira Asyifa Muli": "dT1vK8wP",
    "Davina Athifa Suteza": "kM4nL9pH",
    "Dzaky Al Afifhan": "pF7hJ3rT",
    "Fachry Ramadan Sulistiyo": "qR2kM6wH",
    "Felix Brata": "zL8nG1pS",
    "Felizha Jasmine": "uP5mH4rT",
    "Guntur Fawwaz Vranandha": "fK3cJ9wM",
    "Mhd Kevin Alvaro": "oH7kL2pD",
    "Mhd Harith Riffat Herdzakhwan": "aT9nM8vH",
    "Muhammad Abiyan Al Zabran": "sR4hG6pT",
    "Muhammad Dzaki Maulana": "gM1kN9wH",
    "Muhammad Ghazali": "jF8nL3rG",
    "Muhammad Hilmy Nasution": "pT6cK4tP",
    "Muhammad Syadad Al Ghazy Lubis": "dR9mJ2pS",
    "Nabila Az-Zahra": "kH3nL8wH",
    "Nafiza Asyifa": "oP7kG1rT",
    "Najmi Nurul Khalishah": "uM4nJ9pH",
    "Naufal Rafa Sinulingga": "zK6cL2wT",
    "Raja Fathir Muhammad Lumban Gaol": "fR1kM8pH",
    "Ridho Al Fachri": "qH9nL7rG",
    "Sasya Fairuz Devina Hasibuan": "aT3mG2wP",
    "Sauqi Aleya Ginting": "jP8nK4pS",
    "Zhafirah Anindya Remi": "dF5cL1wH",

    // 9E-1
    "Alvaro Riezky Zafran": "kM9nJ8pT",
    "Annisa Zahiiqa Lubis": "oT2kL6wH",
    "Asyifah Aurelia Zava": "gR7mG1rP",
    "Atha Samy Nuvuz": "uF3hN9pH",
    "Chelsea Jasmine Mei Ji Tan": "dK5nM2wT",
    "Dimas Al Faatih Sulistomo": "zP8kG4rH",
    "Fahmi Al Zakki": "qH1cL7wM",
    "Fajar Akbar Tumangger": "fT6mJ3pS",
    "Fayyadh Naufal Pasyah": "jM4nL8wH",
    "Ghaitsa Wijdaan Batrisya": "aK9kN2rP",
    "Hafizh Hamonangan Nasution": "pR7hG1pH",
    "Harsha Hadya Hrp": "uF3mL9wH",
    "Jihan Talitha Br Ginting": "dT8kG4rH",
    "Khalisyah Rezeki Salsyabilah": "oM1nJ7pT",
    "Mafaaza Mahirah": "gH6mL2wP",
    "Mhd Aqil Aviciena Manik": "zF9nG8rH",
    "Michael Hardian Habeahan": "qR3kJ1wT",
    "Muhammad Faiz Ghaisan": "fM7nL9pH",
    "Muhammad Rizki Alfarizi": "jT4cG2wP",
    "Muhammad Teguh Fahreizy": "aK8nJ3rH",
    "Nailah Rifda Faika": "pF5mG7pH",
    "Qaireen Shadrina": "uT9kL1wM",
    "R Yasha Muhammad Alfaizri": "dM6nJ2rH",
    "Savina Paramesywari Anwar": "oH3cL8wT",
    "Tsasya Muchlishah": "gR7mG1pP",
    "Zahran Dhiya Pasaribu": "zF9kN4rH",
    "Zhilan Zhalila R Nasution": "qT2mL6wH",
    "Zia Anindya Quinza": "fM8nG3pS"    
};